import { DarkTheme, DefaultTheme, Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#ffffff',
    foreground: '#111111',
    card: '#ffffff',
    cardForeground: '#111111',
    popover: '#ffffff',
    popoverForeground: '#111111',
    // Use brand green as app primary on light theme
    primary: '#0e9457',
    primaryForeground: '#ffffff',
    secondary: '#f1f1f1',
    secondaryForeground: '#111111',
    muted: '#f1f1f1',
    mutedForeground: '#919191',
    accent: '#f1f1f1',
    accentForeground: '#111111',
    destructive: '#ff3636',
    border: '#e2e2e2',
    input: '#e2e2e2',
    ring: '#b5b5b5',
    radius: '0.625rem',
    chart1: '#d6652e',
    chart2: '#2f8d7d',
    chart3: '#3b4e7a',
    chart4: '#d7b85d',
    chart5: '#e59c4d',
  },
  dark: {
    background: '#111111',
    foreground: '#ffffff',
    card: '#111111',
    cardForeground: '#ffffff',
    popover: '#111111',
    popoverForeground: '#ffffff',
    // In dark theme, keep primary readable (use white like CSS token)
    primary: '#ffffff',
    primaryForeground: '#111111',
    secondary: '#2b2b2b',
    secondaryForeground: '#ffffff',
    muted: '#2b2b2b',
    mutedForeground: '#8f8f8f',
    accent: '#2b2b2b',
    accentForeground: '#ffffff',
    destructive: '#d24c4c',
    border: '#2b2b2b',
    input: '#2b2b2b',
    ring: '#8e8e8e',
    radius: '0.625rem',
    chart1: '#6e69f1',
    chart2: '#44a68d',
    chart3: '#d88b3a',
    chart4: '#9b7df0',
    chart5: '#e05a93',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      ...DarkTheme.colors,
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
