import { StyleSheet } from 'react-native';

export const detailStyles = StyleSheet.create({
  content: {
    gap: 24,
    paddingBottom: 140,
    marginTop: -24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#FFFFFF',
  },
  pillContainer: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 4,
  },
  pill: {
    width: 42,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#E2E2E2',
  },
  headerSection: {
    gap: 12,
    paddingHorizontal: 16,
  },
  statusIcon: {
    width: 16,
    height: 16,
  },
  chevronIcon: {
    width: 12,
    height: 12,
  },
  backButton: {
    width: 46,
    height: 46,
    borderRadius: 500,
    backgroundColor: 'rgba(17,17,17,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonsGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(17,17,17,0.3)',
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  actionIcon: {
    width: 24,
    height: 24,
  },
  bottomBarShadow: {
    borderTopWidth: 1,
    borderTopColor: '#F1F1F1',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: '#6E6E6E',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 33,
    elevation: 10,
  },
  bottomBar: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 12,
    gap: 12,
  },
  primaryButton: {
    height: 49,
    borderRadius: 12,
    backgroundColor: '#0E9457',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  secondaryButton: {
    height: 49,
    borderRadius: 12,
    backgroundColor: '#F1F1F1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
});
